AWSTemplateFormatVersion: 2010-09-09
Description: "Pipeline resources."
Resources:
  PreprocessingStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: jron-lehtipiste-preprocessing-statemachine
      Tags: 
        - Key: "Owner"
          Value: "Joel Rontynen"
        - Key: "Duedate"
          Value: "2021-12-31"
        - Key: "Schedule"
          Value: "Daily"
      RoleArn: !GetAtt ModelingStepFunctionsWorkflowExecutionRole.Arn
      DefinitionS3Location:
        Bucket: !Sub jron-lehtipiste
        Key: 'preprocessing-statemachine.json'
      DefinitionSubstitutions:
        SagemakerRoleArn: !GetAtt ModelingSagemakerRole.Arn
  ModelingStepFunctionsWorkflowExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: jron-lehtipiste-modeling-stepfunctions-role
      Tags: 
        - Key: "Owner"
          Value: "Joel Rontynen"
        - Key: "Duedate"
          Value: "2021-12-31"
        - Key: "Schedule"
          Value: "Daily"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: SagemakerAccessPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sagemaker:AddTags'
                  - 'sagemaker:CreateProcessingJob'
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - 'events:PutTargets'
                  - 'events:PutRule'
                  - 'events:DescribeRule'
                Resource:
                  - !Sub arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForSageMakerProcessingJobsRule
              - Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource: "*"
                Condition:
                  StringEquals:
                    "iam:PassedToService": "sagemaker.amazonaws.com"
  ModelingSagemakerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: jron-lehtipiste-modeling-sagemaker-role
      Tags: 
        - Key: "Owner"
          Value: "Joel Rontynen"
        - Key: "Duedate"
          Value: "2021-12-31"
        - Key: "Schedule"
          Value: "Daily"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
          - PolicyName: sagemaker-policy
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - "cloudwatch:PutMetricData"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                    - "logs:CreateLogGroup"
                    - "logs:DescribeLogStreams"
                    - "ecr:GetAuthorizationToken"
                    - "ecr:BatchCheckLayerAvailability"
                    - "ecr:GetDownloadUrlForLayer"
                    - "ecr:BatchGetImage"
                  Resource:
                    - "*"
                - Effect: Allow
                  Action: 
                    - "ec2:CreateNetworkInterface"
                    - "ec2:CreateNetworkInterfacePermission"
                    - "ec2:DeleteNetworkInterface"
                    - "ec2:DeleteNetworkInterfacePermission"
                    - "ec2:DescribeNetworkInterfaces"
                    - "ec2:DescribeVpcs"
                    - "ec2:DescribeDhcpOptions"
                    - "ec2:DescribeSubnets"
                    - "ec2:DescribeSecurityGroups"
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - "s3:GetObject"
                    - "s3:PutObject"
                    - "s3:ListBucket"
                  Resource:
                    - !Sub "arn:aws:s3:::va-risk-ranking-${AWS::Region}-${AWS::AccountId}"
                    - !Sub "arn:aws:s3:::va-risk-ranking-${AWS::Region}-${AWS::AccountId}/*"
                    - !Sub "arn:aws:s3:::va-risk-ranking-codes-${AWS::Region}-${AWS::AccountId}"
                    - !Sub "arn:aws:s3:::va-risk-ranking-codes-${AWS::Region}-${AWS::AccountId}/*"
Outputs:
  PreprocessingStateMachineArn:
    Value: !Ref PreprocessingStateMachine
  ModelingStepFunctionsWorkflowExecutionRole:
    Value: !Ref  ModelingStepFunctionsWorkflowExecutionRole
  ModelingSagemakerRole:
    Value: !Ref ModelingSagemakerRole
